sudo: required

notifications:
  email: false

language: rust

before_script:
  - git clone git://github.com/stpettersens/netsh.git
  - cd netsh
  - cargo build --release
  - sudo cp target/release/netsh /usr/bin/_netsh
  - cd ..
