install:
    - ps: Start-FileDownload 'https://static.rust-lang.org/dist/rust-nightly-i686-pc-windows-gnu.exe'
    - rust-nightly-i686-pc-windows-gnu.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
    - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
    - rustc --version
    - cargo --version
    - git clone git://github.com/stpettersens/netsh.git
    - cd netsh
    - cargo build --release
    - cd ..

test_script:
    - cargo test

build: off
